server:
  port: 8088
  error:
    whitelabel:
      enabled: false
spring:
  profiles:
    active: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

service:
  description: User service
  version: 1.0